# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 757418319657335ace5e866fcabc2820871b9b0104e987a3c95bcf7c8dbf940beda8a88187dac91fb07d6671a872d84b7559bdb8407414ad167b53bded73ed61

test:
  secret_key_base: 190db37958424eb729f912d47680cf7771f7d81f58aa513520b6c73781430bd226493a7ed7f2cf87de5eebfc4c69503189a8dd1e46ef6db2e722357338f08b05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
